add_newline = true
command_timeout = 200
format = "[$directory$git_branch$git_status]($style)$character"

[character]
error_symbol = "[✗](bold bright-magenta)"
success_symbol = "[❯](bold bright-magenta)"

[directory]
style = "bright-magenta"
read_only_style = "bright-magenta"
truncation_length = 2
truncation_symbol = "…/"
repo_root_style = "bold bright-magenta"
repo_root_format = "[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "

[git_branch]
format = "[$branch]($style) "
style = "italic bright-magenta"

[git_status]
format     = '[$all_status]($style)'
style      = "bright-magenta"
ahead      = "⇡${count} "
diverged   = "⇕⇡${ahead_count}⇣${behind_count} "
behind     = "⇣${count} "
conflicted = " "
up_to_date = " "
untracked  = "? "
modified   = " "
stashed    = ""
staged     = ""
renamed    = ""
deleted    = ""
