[mode.main.binding]

# Focus movement
cmd-left  = "focus left"
cmd-down  = "focus down"
cmd-up    = "focus up"
cmd-right = "focus right"

# Move windows
cmd-shift-left  = "move left"
cmd-shift-down  = "move down"
cmd-shift-up    = "move up"
cmd-shift-right = "move right"

# Workspace switching (Ctrl + number)
ctrl-1 = "workspace 1"
ctrl-2 = "workspace 2"
ctrl-3 = "workspace 3"
ctrl-4 = "workspace 4"
ctrl-5 = "workspace 5"
ctrl-6 = "workspace 6"
ctrl-7 = "workspace 7"
ctrl-8 = "workspace 8"
ctrl-9 = "workspace 9"

# Next / Previous workspace
ctrl-tab       = "workspace next"
ctrl-shift-tab = "workspace prev"

# Move focused window to workspace
ctrl-shift-1 = "move-node-to-workspace 1"
ctrl-shift-2 = "move-node-to-workspace 2"
ctrl-shift-3 = "move-node-to-workspace 3"
ctrl-shift-4 = "move-node-to-workspace 4"
ctrl-shift-5 = "move-node-to-workspace 5"
ctrl-shift-6 = "move-node-to-workspace 6"
ctrl-shift-7 = "move-node-to-workspace 7"
ctrl-shift-8 = "move-node-to-workspace 8"
ctrl-shift-9 = "move-node-to-workspace 9"


# Fullscreen
cmd-m = "fullscreen"

[gaps]
inner.horizontal = 10  # Gap between windows
inner.vertical = 10
outer.bottom = 10      # Gap between windows and monitor edges
outer.top = 10
outer.left = 10
outer.right = 10

